baseURL = "https=//btcz.im"
languageCode = "en-us"
title = "Zen of Bitcoin"

theme = "terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = false
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[languages]
  [languages.en]
    title = "Zen of Bitcoin"
    subtitle = "Understanding the Bitcoin"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Zen of Bitcoin"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "grid"
        name = "Grid Trade"
        url = "."
        weight= 2
      [[languages.en.menu.main]]
        identifier = "bitcoin"
        name = "Bitcoin"
        url = "."
        weight= 1           
      [[languages.en.menu.main]]
        identifier = "books"
        name = "Books"
        url = "."
        weight= 4
      [[languages.en.menu.main]]
        identifier = "ielts"
        name = "IELTS"
        url = "."
        weight= 3
      [[languages.en.menu.main]]
        identifier = "ieltspeak"
        name = "IELTS Speak"
        url = "."
        weight= 1
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/index.html"
        weight= 5