baseURL = "https://btcz.im"
languageCode = "en-us"
title = "Zen of Bitcoin"

paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = false
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[taxonomies]
  tag = "tags"
  category = "categories"

[languages]
  [languages.en]
    title = "Zen of Bitcoin"
    subtitle = "Understanding the Bitcoin"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Zen of Bitcoin"
      logoHomeLink = "/"

    [languages.en.menu]
